---

- name: Update apt package cache
  apt: update_cache=yes

- name: Install required system packages
  apt: >
    name="{{ item }}"
    update_cache=yes
    state=latest
  with_items: tentacool_system_packages

- name: Create user for running tentacool
  user: >
    name="{{ tentacool_username }}"
    home="/home/{{ tentacool_username }}"

- name: Create tentacool folder
  file: >
    dest="{{ tentacool_dir }}"
    state=directory owner="{{ tentacool_username }}" mode=755

- name: Checkout tentacool source
  git: >
    repo=https://github.com/tentacool/tentacool
    dest="{{ tentacool_dir }}"
  register: checkout

- name: Generate tentacool build configure
  shell: autoreconf -i
  args:
    chdir: "{{ tentacool_dir }}"
  when: checkout.changed

- name: Configures tentacool build
  shell: ./configure
  args:
    chdir: "{{ tentacool_dir }}"
  when: checkout.changed

- name: Build tentacool
  shell: make
  args:
    chdir: "{{ tentacool_dir }}"
  when: checkout.changed
    
- name: Install tentacool
  shell: make install
  args:
    chdir: "{{ tentacool_dir }}"
  when: checkout.changed

- name: Copy init.d script for tentacool
  template: >
    src=tentacool.sh
    dest="/etc/init.d/{{ tentacool_service }}" owner=root mode=755

- name: Create init.d config for tentacool
  template: >
    src=tentacool
    dest="/etc/default/{{ tentacool_service }}" owner=root mode=755

- name: Write tentacool auth file
  template: >
    src=auth_keys.dat
    dest="{{ tentacool_auth_file }}" owner=root mode=755

- name: Add tentacool service
  service: name="{{ tentacool_service }}" enabled=yes state=started
  